version: '3.8'

services:
  frontsarsmomo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontsarsmomo
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3601
    ports:
      - "3601:3601"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontsarsmomo.rule=Host(`stars.qashmo.com`)"
      - "traefik.http.routers.frontsarsmomo.entrypoints=websecure"
      - "traefik.http.routers.frontsarsmomo.tls=true"
      - "traefik.http.routers.frontsarsmomo.tls.certresolver=myresolver"
      - "traefik.http.services.frontsarsmomo.loadbalancer.server.port=3601"
    networks:
      - traefik
    expose:
      - "3601"

networks:
  traefik:
    external: true